export var SIGNINEMAILPASS = "SIGNINEMAILPASS";
export var LOGINWITHFACEBOOK = "LOGINWITHFACEBOOK"
export var SIGNOUT = "SIGNOUT";
export var SIGNUP = "SIGNUP";
export var SETUSER = "SETUSER"
export var SETLOCATION = "SET_LOCATION"